# -*- coding: utf-8 -*-
"""Green_cycle_backup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWAVOSYBuXiBHwLhzMXEn2EgCfrLtpUz
"""

!pip install Kaggle

import os, shutil

# kaggle.json setup - works in Colab AND on a local machine.
# A missing kaggle.json is only fatal if the dataset is missing too.
kaggle_dir = os.path.expanduser("~/.kaggle")
have_key = os.path.exists(os.path.join(kaggle_dir, "kaggle.json"))

if os.path.isdir("/content") and not have_key:        # Google Colab -> prompt upload
    try:
        from google.colab import files
        uploaded = files.upload()                      # upload kaggle.json when prompted
        if uploaded:
            os.makedirs(kaggle_dir, exist_ok=True)
            shutil.copy("kaggle.json", os.path.join(kaggle_dir, "kaggle.json"))
            have_key = True
    except Exception as e:
        print("Upload skipped:", e)
elif not have_key and os.path.exists("kaggle.json"):   # local -> file next to the notebook
    os.makedirs(kaggle_dir, exist_ok=True)
    shutil.copy("kaggle.json", os.path.join(kaggle_dir, "kaggle.json"))
    have_key = True

if os.name != "nt" and have_key:
    os.chmod(os.path.join(kaggle_dir, "kaggle.json"), 0o600)

if have_key:
    print("kaggle.json ready in", kaggle_dir)
else:
    print("kaggle.json not found - that is fine if the dataset folder already exists.")
    print("Otherwise: place kaggle.json next to this notebook (or run in Colab), then re-run.")

import os

if any(os.path.isdir(d) for d in ["standardized_256", "standardized_384"]):
    print("Dataset already present - skipping download.")
else:
    print("Downloading dataset from Kaggle...")
    !kaggle datasets download -d sumn2u/garbage-classification-v2
    !unzip -q -o garbage-classification-v2.zip

!pip install tensorflow opencv-python scikit-learn matplotlib seaborn fastapi uvicorn python-multipart

"""## Data Importation

"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
import cv2
from PIL import Image
import json
from collections import defaultdict
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import torch
import torch.nn as nn

print("="*60)
print("CHECKING SETUP")
print("="*60)
print(f"TensorFlow version: {tf.__version__}")
gpu_available = len(tf.config.list_physical_devices('GPU')) > 0
print(f"GPU Available: {gpu_available}")
if gpu_available:
    print(f"GPU Device: {tf.config.list_physical_devices('GPU')[0].name}")
else:
    print(" No GPU - training will be SLOW. Switch to GPU in Colab: Runtime → Change Runtime Type → T4")

print("✓ Imports successful")

# Verify GPU is working
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
print("="*60)
print("GPU VERIFICATION")
print("="*60)
print(f"Number of GPUs: {len(gpus)}")

if len(gpus) > 0:
    print(f"✓ GPU Device: {gpus[0].name}")
    print("✓ GPU IS ACTIVE - Training will be FAST!")

    # Show GPU memory
    print(f"\nGPU Memory:")
    for gpu in gpus:
        print(f"  {gpu}")
else:
    print("✗ Still no GPU. Try:")
    print("  1. Runtime → Restart runtime")
    print("  2. Then Runtime → Change Runtime Type → T4")

import os, zipfile, subprocess

# Locate (or download) the dataset once and set DATA_DIR for the whole notebook
CANDIDATES = ["standardized_256", "standardized_384"]
DATA_DIR = next((d for d in CANDIDATES if os.path.isdir(d)), None)

if DATA_DIR is None:
    print("No standardized_* folder found - downloading dataset from Kaggle...")
    if not os.path.exists(os.path.expanduser("~/.kaggle/kaggle.json")):
        raise FileNotFoundError("kaggle.json missing - run the kaggle.json setup cell above first.")
    subprocess.run(["kaggle", "datasets", "download", "-d",
                    "sumn2u/garbage-classification-v2", "-p", ".", "--force"], check=True)
    with zipfile.ZipFile("garbage-classification-v2.zip") as z:
        z.extractall(".")
    DATA_DIR = next((d for d in CANDIDATES if os.path.isdir(d)), None)

assert DATA_DIR is not None, ("Dataset still missing. Folders here: " + str(sorted(os.listdir("."))))
print("DATA_DIR =", DATA_DIR)

categories = sorted(d for d in os.listdir(DATA_DIR) if os.path.isdir(os.path.join(DATA_DIR, d)))
class_counts = {}
for cat in categories:
    path = os.path.join(DATA_DIR, cat)
    class_counts[cat] = len([f for f in os.listdir(path)
                             if f.lower().endswith((".jpg", ".jpeg", ".png"))])

print("Categories and image counts:")
for cat, n in class_counts.items():
    print(f"  {cat}: {n}")
print()
print(f"Total images: {sum(class_counts.values())}")
print(f"Class imbalance ratio (max/min): {max(class_counts.values()) / min(class_counts.values()):.2f}x")

# DataFrame for the cells below (describe / countplot / imbalance ratio)
df = pd.DataFrame(sorted(class_counts.items()), columns=["Category", "Count"])
print(df)

data = {
    'battery': 756,
    'biological': 699,
    'cardboard': 1411,
    'clothes': 1892,
    'glass': 1736,
    'metal': 930,
    'paper': 1336,
    'plastic': 1597,
    'shoes': 1449,
    'trash': 453,

  }

df = pd.DataFrame(list(data.items()),columns=["Category","Count"])

print("Class distribution:\n",df)

df.describe()

#Countplot
plt.figure(figsize=(10,6))
sns.barplot(x="Category", y="Count", data=df, palette="viridis")
plt.title("Image Count per Category")
plt.ylabel("Number of Images")
plt.show()

imbalance_ratio = df["Count"].max() / df["Count"].min()
print(f"Total images: {df['Count'].sum()}")
print(f"Class imbalance ratio (max/min): {imbalance_ratio:.2f}x")

# Handling class imbalance -- class weights in Keras format
counts = {
    'battery': 756, 'biological': 699, 'cardboard': 1411, 'clothes': 1892,
    'glass': 1736, 'metal': 930, 'paper': 1336, 'plastic': 1597,
    'shoes': 1449, 'trash': 453
}
total = sum(counts.values())
class_weight = {i: total / (len(counts) * n) for i, (_, n) in enumerate(sorted(counts.items()))}
print("Class weights (index -> weight):")
for k, v in class_weight.items():
    print(f"  {k}: {v:.3f}")
# Pass to model.fit(class_weight=class_weight) below

# Data augmentation
from tensorflow.keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(
    rotation_range = 20,
    width_shift_range = 0.1,
    height_shift_range = 0.1,
    shear_range =0.1,
    zoom_range = 0.1,
    horizontal_flip= True,
    fill_mode = 'nearest'
)

# Visualize what the augmentation pipeline produces (for the report)
aug_preview = datagen.flow_from_directory(
    DATA_DIR,
    target_size=(224, 224),
    batch_size=5,
    class_mode="categorical",
    shuffle=True
)
imgs, _ = next(aug_preview)
plt.figure(figsize=(12, 4))
for i in range(5):
    plt.subplot(1, 5, i + 1)
    plt.imshow(imgs[i])
    plt.axis("off")
plt.suptitle("Augmented sample images")
plt.show()

"""## Build Model

"""

print(sorted(os.listdir(DATA_DIR)))

#Data preparation
train_datagen = ImageDataGenerator(
    preprocessing_function= preprocess_input,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8,1.2],
    validation_split = 0.2
)

val_datagen =ImageDataGenerator(
     preprocessing_function= preprocess_input,
     validation_split=0.2
)
train_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=(224,224),
    batch_size=32,
    class_mode = "categorical",
    subset = "training"
)

val_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    subset="validation",
    shuffle=False  # REQUIRED: keeps y_true aligned with predictions
)

IMG_SIZE=(224,224)
NUM_CLASSES = len(val_generator.class_indices)

base_model= MobileNetV2(
    weights="imagenet",
    include_top = False,
    input_shape =IMG_SIZE + (3,),
)

base_model.trainable = False

inputs = layers.Input(shape = IMG_SIZE + (3,))
x = base_model(inputs,training= False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
x = layers.Dense(128,activation="relu")(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(NUM_CLASSES,activation="softmax")(x)

model =Model(inputs,outputs)

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
              )
model.summary()

from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
lr_reduce = ReduceLROnPlateau(monitor="val_loss", factor=0.3,patience=2,min_lr=1e-6)

print("train batches:",len(train_generator))
print("val_batches:",len(val_generator))

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10,
    class_weight=class_weight,   # rebalances loss for minority classes
    callbacks=[early_stop,lr_reduce],
)

base_model.trainable = True
for layer in base_model.layers[:-30]:
  layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate= 1e-5),
    loss= "categorical_crossentropy",
    metrics=["accuracy"],
)

#fine_tuining
history_ft = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5,
    class_weight=class_weight,   # rebalances loss for minority classes
    callbacks=[early_stop,lr_reduce],
)

# Predictions -- val_generator has shuffle=False, so .labels aligns with the
# order in which model.predict() walks the generator
y_pred = model.predict(val_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = val_generator.labels
assert len(y_true) == len(y_pred_classes), "Label/prediction misalignment!"

print(classification_report(y_true,y_pred_classes, target_names=list(val_generator.class_indices.keys())))

##Confusion Matrix
cm = confusion_matrix(y_true,y_pred_classes)
plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=list(val_generator.class_indices.keys()),
            yticklabels=list(val_generator.class_indices.keys()))
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

##Save model
model.save('my_model.keras')

"""## Training Curves

## Safety-Critical Analysis: Battery False Negatives

A false negative on **battery** (hazardous material) is costlier than a false positive, so raw accuracy is not the right headline metric. We report battery recall explicitly, plus per-class recall for other hazardous/minority classes.
"""

report = classification_report(
    y_true, y_pred_classes,
    target_names=list(val_generator.class_indices.keys()),
    output_dict=True
)
print(f"Overall accuracy: {report['accuracy']:.2%}")
print(f"Macro F1: {report['macro avg']['f1-score']:.2%}")
print()
for cls in ['battery', 'biological', 'metal', 'trash']:
    print(f"Recall for {cls}: {report[cls]['recall']:.2%}")
print()
batt = report['battery']['recall']
print(f"Battery recall (safety-critical): {batt:.2%} -- "
      + ("acceptable" if batt >= 0.9 else "BELOW the 90% target; route low-confidence battery predictions to a human sorter"))